### PR TITLE
Added a new plugin: Markly

### PR DESCRIPTION
**Pull request by freWalker**
Markly is a measure and design spec plugin/extension for Photoshop & Sketch.

### CODE REVIEW

**Comment by florianbuerger** [comment]
Thanks!

**Comment by freWalker** [comment]
Dear Florian,

I just check the plugin Markly has been merged to the master branch, but it is not be listed in awesome-sket.ch.
Could you please to help me to check it?

Thanks,

Lance

**Comment by florianbuerger** [comment]
Sorry, the deploy script didn’t ran correctly. I’ve deployed it manually just a moment ago, you should see it now :wink:

**Comment by freWalker** [comment]
Cheers! :-)

**Pull request merged**
